import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowDownRight, ArrowRight, ArrowUpRight, BookOpen, Check, Clock3, Lightbulb, MoveUpRight, ShieldCheck, Sparkles, Zap } from 'lucide-react';
import { siteConfig } from '@/lib/constants';

export const metadata: Metadata = {
  title: 'Electrical Insights & Advice',
  description: 'Practical electrical advice, safety guides, product explainers, and project insights from the PowerFix team.',
  alternates: { canonical: `${siteConfig.canonicalUrl}/blog` }
};

const articles = [
  { category: 'Safety', title: '7 warning signs your home wiring needs an inspection', excerpt: 'Small electrical symptoms can become expensive hazards. Learn what to notice before a minor issue turns serious.', date: 'May 18, 2026', readTime: '6 min read', image: '/services/engineer_hero.png', tone: 'from-[#0a3154] to-[#09223d]' },
  { category: 'Guides', title: 'How to choose the right MCB for every circuit', excerpt: 'A practical guide to ratings, protection zones, and the details that make a distribution board safer.', date: 'May 11, 2026', readTime: '5 min read', image: 'https://images.unsplash.com/photo-1555618568-211cf84456ca?auto=format&fit=crop&w=1000&q=85', tone: 'from-[#154d65] to-[#0a2d3c]' },
  { category: 'Energy', title: 'Simple ways to lower your monthly power use', excerpt: 'Efficient lighting, better load planning, and a few everyday habits can make a measurable difference.', date: 'May 04, 2026', readTime: '4 min read', image: 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=1000&q=85', tone: 'from-[#315b46] to-[#1b352f]' },
  { category: 'Projects', title: 'Inside a clean, future-ready office installation', excerpt: 'A look at how structured wiring and thoughtful panel planning help workplaces stay flexible.', date: 'April 26, 2026', readTime: '7 min read', image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1000&q=85', tone: 'from-[#4b3d32] to-[#241f1d]' },
  { category: 'Maintenance', title: 'The seasonal electrical maintenance checklist', excerpt: 'Use this simple checklist to prepare fans, pumps, backup power, and outdoor circuits for the season ahead.', date: 'April 18, 2026', readTime: '5 min read', image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=85', tone: 'from-[#164c61] to-[#102b43]' },
  { category: 'Products', title: 'What to look for in quality electrical accessories', excerpt: 'Genuine materials are about more than packaging. Here are the details worth checking before you buy.', date: 'April 10, 2026', readTime: '6 min read', image: 'https://images.unsplash.com/photo-1558008258-3256797b43f3?auto=format&fit=crop&w=1000&q=85', tone: 'from-[#574330] to-[#2e261e]' }
];

const topics = [
  { label: 'Safety first', count: '08 reads', icon: ShieldCheck },
  { label: 'Energy smart', count: '06 reads', icon: Lightbulb },
  { label: 'Project notes', count: '05 reads', icon: Sparkles },
  { label: 'Pro guides', count: '11 reads', icon: BookOpen }
];

type Article = (typeof articles)[number];

function Meta({ article }: { article: Article }) {
  return <div className="flex items-center gap-3 text-[10px] font-extrabold uppercase tracking-[0.16em] text-slate-400"><span>{article.date}</span><span className="h-1 w-1 rounded-full bg-amber-400" /><span className="inline-flex items-center gap-1"><Clock3 size={13} /> {article.readTime}</span></div>;
}

export default function BlogPage() {
  const featured = articles[0];

  return (
    <main className="overflow-hidden bg-[#f4f7f5] text-[#102638]">
      <section className="relative isolate overflow-hidden bg-[#08243a] text-white">
        <div className="absolute inset-0 bg-[url('/Blog-hero.webp')] bg-cover bg-center opacity-45 mix-blend-screen transition duration-[1400ms] hover:scale-105 hover:opacity-55" />
        <div className="absolute inset-0 bg-[linear-gradient(100deg,#061a2c_4%,rgba(6,26,44,0.94)_35%,rgba(6,26,44,0.52)_72%,rgba(6,26,44,0.88)_100%)]" />
        <div className="absolute right-[-10%] top-[-32%] h-[620px] w-[620px] rounded-full border border-cyan-200/10" />
        <div className="absolute right-[4%] top-[-18%] h-[430px] w-[430px] rounded-full border border-amber-300/10" />
        <div className="container-shell relative grid min-h-[650px] items-center gap-14 py-24 lg:grid-cols-[1fr_310px] lg:py-28">
          <div className="max-w-3xl animate-[fadeInUp_700ms_ease-out_both]">
            <div className="flex items-center gap-3 text-[11px] font-extrabold uppercase tracking-[0.26em] text-amber-300"><span className="h-px w-10 bg-amber-300" /> The PowerFix Journal</div>
            <h1 className="mt-7 max-w-3xl font-[var(--font-display)] text-5xl font-extrabold leading-[0.96] tracking-[-0.04em] sm:text-7xl lg:text-[6.7rem]">Good work starts with <span className="text-[#f6c548]">knowing.</span></h1>
            <p className="mt-7 max-w-xl text-base leading-8 text-slate-200 sm:text-lg">Field-tested electrical knowledge for safer homes, sharper decisions, and projects that perform beautifully.</p>
            <div className="mt-9 flex flex-wrap items-center gap-5"><Link href="#featured" className="group inline-flex items-center gap-3 rounded-full bg-[#f6c548] px-6 py-3.5 text-sm font-extrabold text-[#102638] shadow-[0_16px_38px_rgba(246,197,72,0.2)] transition duration-300 hover:-translate-y-1 hover:bg-[#ffdc70] hover:shadow-[0_20px_45px_rgba(246,197,72,0.35)]">Explore the latest <ArrowDownRight size={17} className="transition group-hover:rotate-[-45deg]" /></Link><span className="inline-flex items-center gap-2 text-sm font-semibold text-slate-300"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400" /> New field notes every week</span></div>
          </div>
          <div className="hidden animate-[fadeInUp_900ms_180ms_ease-out_both] lg:block"><div className="border-l border-white/20 pl-7"><p className="text-[10px] font-extrabold uppercase tracking-[0.25em] text-slate-400">Inside this issue</p><div className="mt-7 space-y-5">{['Home wiring signals', 'Safer circuit choices', 'Smarter energy habits'].map((item, index) => <Link href="#articles" key={item} className="group flex items-start gap-4 border-b border-white/10 pb-5"><span className="font-mono text-xs text-amber-300">0{index + 1}</span><span className="text-sm font-bold text-slate-200 transition group-hover:text-amber-300">{item}</span><ArrowUpRight size={15} className="ml-auto text-slate-500 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-white" /></Link>)}</div><p className="mt-7 text-xs leading-5 text-slate-400">Written with technicians, engineers, and the people who keep things running.</p></div></div>
        </div>
        <div className="absolute bottom-0 left-0 h-16 w-full bg-gradient-to-t from-[#f4f7f5] to-transparent" />
      </section>

      <section className="container-shell relative z-10 -mt-1 py-16 sm:py-20" id="featured">
        <div className="mb-8 flex items-end justify-between gap-5"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.24em] text-blue-700">01 / The lead story</p><h2 className="mt-3 font-[var(--font-display)] text-3xl font-extrabold tracking-[-0.03em] sm:text-5xl">Start with the essentials.</h2></div><span className="hidden text-right text-xs font-semibold leading-5 text-slate-500 sm:block">One useful read<br />before the next job.</span></div>
        <article className="group relative grid overflow-hidden rounded-[2rem] bg-[#0b2c47] text-white shadow-[0_28px_80px_rgba(14,47,71,0.2)] lg:grid-cols-[1.1fr_0.9fr]">
          <div className="relative min-h-[330px] overflow-hidden lg:min-h-[510px]"><Image src={featured.image} alt={featured.title} fill priority sizes="(max-width: 1024px) 100vw, 60vw" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-r from-[#09243b]/15 via-transparent to-[#09243b]/70" /><span className="absolute left-6 top-6 rounded-full border border-white/25 bg-[#09243b]/60 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[0.17em] text-amber-200 backdrop-blur">{featured.category} / Editor&apos;s pick</span></div>
          <div className="relative flex flex-col justify-center overflow-hidden p-8 sm:p-12 lg:p-14"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full border border-cyan-200/10" /><div className="relative"><Meta article={featured} /><h3 className="mt-6 font-[var(--font-display)] text-3xl font-extrabold leading-[1.05] tracking-[-0.03em] sm:text-5xl">{featured.title}</h3><p className="mt-6 max-w-md text-base leading-7 text-slate-300">{featured.excerpt}</p><Link href="#articles" className="group/link mt-9 inline-flex w-fit items-center gap-3 border-b border-amber-300 pb-2 text-sm font-extrabold text-amber-200 transition hover:border-white hover:text-white">Read the field note <ArrowRight size={17} className="transition group-hover/link:translate-x-1" /></Link></div></div>
        </article>
      </section>

      <section className="border-y border-[#d9e3e0] bg-[#eaf1ef] py-8"><div className="container-shell grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{topics.map(({ label, count, icon: Icon }, index) => <Link href="#articles" key={label} className="group flex items-center gap-4 rounded-2xl border border-transparent px-4 py-3 transition duration-300 hover:-translate-y-1 hover:border-[#c8d9d5] hover:bg-white hover:shadow-[0_12px_30px_rgba(21,60,69,0.08)]"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-blue-700 shadow-sm transition group-hover:bg-[#0b2c47] group-hover:text-amber-300"><Icon size={18} /></span><span><span className="block text-sm font-extrabold text-[#17384d]">{label}</span><span className="mt-0.5 block text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">{count}</span></span><span className="ml-auto font-mono text-xs text-slate-300">0{index + 1}</span></Link>)}</div></section>

      <section id="articles" className="container-shell py-20 sm:py-28"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.24em] text-blue-700">02 / More to explore</p><h2 className="mt-3 max-w-xl font-[var(--font-display)] text-3xl font-extrabold tracking-[-0.03em] sm:text-5xl">Useful ideas, clearly explained.</h2></div><div className="flex items-center gap-2 text-sm font-semibold text-slate-500"><Lightbulb size={17} className="text-amber-500" /> Safety first. Always.</div></div><div className="mt-12 grid gap-x-6 gap-y-12 md:grid-cols-2 xl:grid-cols-3">{articles.slice(1).map((article, index) => <article key={article.title} className="group animate-[fadeInUp_700ms_ease-out_both] overflow-hidden rounded-[1.5rem] border border-[#dce6e3] bg-white shadow-[0_8px_25px_rgba(21,60,69,0.04)] transition duration-500 hover:-translate-y-2 hover:border-[#b8ceca] hover:shadow-[0_22px_45px_rgba(21,60,69,0.13)]" style={{ animationDelay: `${index * 90}ms` }}><div className="relative aspect-[1.35] overflow-hidden"><Image src={article.image} alt={article.title} fill sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-110" /><div className={`absolute inset-0 bg-gradient-to-t ${article.tone} opacity-15 transition duration-500 group-hover:opacity-35`} /><span className="absolute left-4 top-4 rounded-full border border-white/30 bg-[#102638]/65 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[0.16em] text-white backdrop-blur">{article.category}</span><span className="absolute bottom-4 right-4 flex h-9 w-9 translate-y-2 items-center justify-center rounded-full bg-white text-[#102638] opacity-0 shadow-lg transition duration-300 group-hover:translate-y-0 group-hover:opacity-100"><MoveUpRight size={16} /></span></div><div className="p-6"><Meta article={article} /><h3 className="mt-4 font-[var(--font-display)] text-xl font-extrabold leading-tight tracking-[-0.02em] transition group-hover:text-blue-700">{article.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{article.excerpt}</p><Link href="#" className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-[#102638] transition group-hover:text-blue-700">Read article <ArrowRight size={15} className="transition group-hover:translate-x-1" /></Link></div></article>)}</div></section>

      <section className="container-shell pb-20 sm:pb-28"><div className="relative overflow-hidden rounded-[2rem] bg-[#f6c548] px-7 py-12 shadow-[0_25px_70px_rgba(144,108,18,0.18)] sm:px-12 lg:flex lg:items-center lg:justify-between lg:gap-12 lg:px-16 lg:py-16"><div aria-hidden="true" className="pointer-events-none absolute inset-0 bg-[url('/blog_cta.png')] bg-cover bg-center opacity-50" /><div aria-hidden="true" className="pointer-events-none absolute inset-0 bg-[#f6c548]/55" /><div className="absolute -right-24 -top-28 h-80 w-80 animate-[float_6s_ease-in-out_infinite] rounded-full border-[34px] border-white/20" /><div className="relative z-10 max-w-2xl animate-[fadeInUp_700ms_ease-out_both]"><div className="inline-flex items-center gap-2 text-[11px] font-extrabold uppercase tracking-[0.2em] text-[#4d3b0f]"><Zap size={14} fill="currentColor" /> 03 / Stay switched on</div><h2 className="mt-4 font-[var(--font-display)] text-3xl font-extrabold leading-tight tracking-[-0.03em] text-[#102638] sm:text-5xl">A little knowledge goes a long way.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-[#4d3b0f]">Get occasional safety tips, product explainers, and maintenance reminders from the PowerFix team.</p><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-xs font-bold text-[#4d3b0f]"><span className="inline-flex items-center gap-2"><Check size={14} /> No noisy inbox</span><span className="inline-flex items-center gap-2"><Check size={14} /> Useful by design</span></div></div><form className="relative z-10 mt-8 flex w-full max-w-xl animate-[fadeInUp_700ms_150ms_ease-out_both] flex-col gap-3 sm:flex-row lg:mt-0" action="#"><input type="email" required placeholder="Your email address" aria-label="Your email address" className="min-h-13 flex-1 rounded-xl border border-[#9c7a1e] bg-white/80 px-4 text-sm text-[#102638] outline-none placeholder:text-[#806b2e] focus:border-[#102638] focus:ring-4 focus:ring-[#102638]/10" /><button type="submit" className="inline-flex min-h-13 items-center justify-center gap-2 rounded-xl bg-[#102638] px-5 text-sm font-extrabold text-white transition hover:-translate-y-1 hover:bg-[#173f5a] hover:shadow-[0_12px_24px_rgba(16,38,56,0.25)]">Join the journal <ArrowRight size={16} /></button></form></div></section>
    </main>
  );
}
